apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx-operator-controller-manager
  namespace: system
  labels:
    app: awx-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awx-operator
  template:
    metadata:
      labels:
        app: awx-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: manager
        image: ${IMG}
        imagePullPolicy: Always
        args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8080
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccountName: awx-operator
      terminationGracePeriodSeconds: 10 