apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awx-operator-role
rules:
- apiGroups: ["awx.ansible.com"]
  resources: ["awxinstances"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["awx.ansible.com"]
  resources: ["awxinstances/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["awx.ansible.com"]
  resources: ["awxinstances/finalizers"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"] 