apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awx-operator-role
rules:
- apiGroups: ["awx.example.com"]
  resources: ["awxinstances"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["awx.example.com"]
  resources: ["awxinstances/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["awx.example.com"]
  resources: ["awxinstances/finalizers"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"] 