apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/derzufall/awx-k8s-operator.git
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - argocd/values.yaml
      parameters:
        - name: operator.image.registry
          value: quay.io
        - name: operator.image.repository
          value: wolkenzentrale/awx-operator
        - name: operator.image.tag
          value: aed406c
        - name: operator.reconciliation.period
          value: "60"
  destination:
    server: https://kubernetes.default.svc
    namespace: awx-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 