apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/awx-k8s-operator.git  # Replace with your Git repo URL
    targetRevision: HEAD
    path: .
    kustomize:
      # You can add specific kustomize options here if needed
      # For example, to set image parameters from ArgoCD:
      images:
        - quay.io/myuser/awx-operator:latest # This will be replaced by kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: awx-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 