apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: awx-operator
  namespace: argocd
spec:
  generators:
    # Use matrix generator to combine clusters with environments
    - matrix:
        generators:
          # List of clusters to deploy to
          - list:
              elements:
                - cluster: in-cluster
                  url: https://kubernetes.default.svc
                  environment: production
                - cluster: dev-cluster
                  url: https://dev-cluster-api.example.com
                  environment: development
                # Add more clusters as needed
          
          # List of environments with their configurations
          - list:
              elements:
                - environment: production
                  namespace: awx-operator-system
                  valueFiles:
                    - values-production.yaml
                - environment: development
                  namespace: awx-operator-dev
                  valueFiles:
                    - values-dev.yaml
                # Add more environments as needed
  
  template:
    metadata:
      name: 'awx-operator-{{cluster}}-{{environment}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/yourusername/awx-k8s-operator.git # Replace with your repo
        targetRevision: HEAD
        path: .
        
        # Kustomize configurations
        kustomize:
          images:
            - '{{values.operator.image.registry}}/{{values.operator.image.repository}}:{{values.operator.image.tag}}'
          
          # Optional value overrides
          commonLabels:
            environment: '{{environment}}'
          
          # Pull values from values file
          valueFiles:
            - '$path/argocd/{{valueFiles}}'
      
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m 