operator:
  image:
    registry: quay.io
    repository: myuser/awx-operator
    tag: latest
    pullPolicy: Always
  
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  reconciliation:
    period: 30  # faster reconciliation for dev/testing
  
  logs:
    level: debug  # more verbose logging for development

# Development settings
replicas: 1

# Namespace settings
namespace: awx-operator-dev 