operator:
  image:
    registry: quay.io
    repository: wolkenzentrale/awx-operator
    tag: aed406c
    pullPolicy: Always
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  
  reconciliation:
    period: 30  # faster reconciliation for development
  
  logs:
    level: debug  # more verbose logging for development

# Namespace settings
namespace: awx-operator-dev
createNamespace: true

# Development settings
replicas: 1

# ArgoCD application settings
argocd:
  project: default
  server: https://kubernetes.default.svc
  automated:
    prune: true
    selfHeal: true 